### ISSUE TITLE
Assertion 'params->_type==CPU' failed

### ISSUE THREAD

**Issue by charles3378** [NervanaSystems/neon_segnet#2]
I am trying to run neon_segnet.py. And follow issue was found "Python: src/device.hpp: static Device\* Device:: create(DeviceParams): Assertion 'params->_type==CPU' failed.

It may not be the installation issue. I can run the neon examples with both -b cpu and -b gpu.  They worked fine.

**Comment by nervetumer** [comment]
As written in the readme:

There is no CPU backend support for this model, it requires a Maxwell class GPU.

It should not be too difficult to add a CPU version of the upsampling layer, but it is currently not a high priority.  It you want to submit a PR with a CPU upsampling layer that would be great.

**Comment by charles3378** [comment]
Thanks, problem has been resolved. It turns out that neon version 1.5.4 has this issue. It run OK when I switched back to v1.5.3.
